# Generated by Django 5.2 on 2026-07-13 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='cruises/')),
                ('description', models.TextField()),
                ('from_port', models.CharField(max_length=100)),
                ('to_port', models.CharField(max_length=100)),
                ('duration_hours', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cruises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='active', max_length=20)),
                ('total_seats', models.PositiveIntegerField(default=60)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cruises.cruise')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['date', 'departure_time'],
                'unique_together': {('cruise', 'date', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('row_label', models.CharField(db_index=True, max_length=10)),
                ('position', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('held', 'Held (awaiting payment)')], default='available', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cruises.schedule')),
            ],
            options={
                'db_table': 'seats',
                'ordering': ['seat_number'],
                'unique_together': {('schedule', 'seat_number')},
            },
        ),
    ]
