# Generated by Django 5.2 on 2026-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_address',
            field=models.TextField(default=''),
        ),
    ]
