# Generated by Django 5.2 on 2026-07-13 08:45

import django.db.models.deletion
import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=30, unique=True)),
                ('qr_code', models.ImageField(blank=True, upload_to=tickets.models.ticket_qr_path)),
                ('pdf', models.FileField(blank=True, upload_to=tickets.models.ticket_pdf_path)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='bookings.booking')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
    ]
